Repository Swarmies/sap-core, pull requests merged in 2022-06, with the labels that each got.

#30 CircleCI
  .circleci/config.yml
Labels: enhancement

#26 Scaffold
  .circleci/config.yml
  .dockerignore
  .vscode/settings.json
  Dockerfile
  README.md
  docker-compose.yml
  frontend/Dockerfile
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  manage.py
  requirements.txt
  sapweb/__init__.py
  sapweb/asgi.py
  sapweb/settings.py
  sapweb/urls.py
  sapweb/wsgi.py
Labels: New Feature

#44 updated documentation on ER_diagram
  Doc/ER_diagram.md
Labels: documentation
